# Needs revision

on: [push, pull_request]
name: Test
env:
  ENV: "TEST"
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x, 1.17.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Go ${{ matrix.go }} tests
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -race -timeout 60s ./...
